### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/ntu120/NTU120_CSet.npz'

### ISSUE THREAD

**Issue by zoeyhaiyan1** [Necolizer/ISTA-Net#3]
I have the problem mentioned above. Can you give me a answer. Thanks.

**Comment by Necolizer** [comment]
Hi @zoeyhaiyan1, did you follow the instructions to [prepare the NTU dataset](https://github.com/Necolizer/ISTA-Net#31-ntu-rgbd-120--ntu-mutual)? After your preporocess, you should get NTU120_CSet.npz. Make sure the path to this zip file is correct.
