### ISSUE TITLE
关于实验

### ISSUE THREAD

**Issue by zangtuo** [Necolizer/ISTA-Net#4]
感谢作者的工作，给了我很多启发。我对文章中复现的实验有一些疑问，我看你在NTU多人样本中复现了一些骨架动作识别领域以往的sota方法HD-GCN、info-GCN和LST等，你是完全按照原来文章的模型和训练方法训练的吗，另外STSA-Net的作者其实并没有完全公开自己的代码，他公开的是挂在arxiv上的sttformer版本，不知道这里你是如何处理的，还望赐教。

**Comment by Necolizer** [comment]
您好，
1. 您这里提到的HD-GCN、info-GCN和LST，我是取他们各自公开的代码做的训练和测试，表格2中展示的是多次不同Seed跑训练+测试的均值和标准差。我只选择了joint模态进行评估（他们原论文中可能有做joint/bone/joint motion/bone motion等多模态融合，但我的表2中都是只选择一个joint模态进行评估，我已在我论文IV. EXPERIMENTS的A. Datasets最后一段提及），这是为了跟表格2中我引用的[15]文章的实验数据的评判标准保持一致。
2. STSA-Net只有arxiv上的sttformer版本的开源代码，这个没错。我参照[STSA-Net论文](https://www.sciencedirect.com/science/article/pii/S0925231222013716)的Fig.2与4.2章节和sttformer版本的开源代码，自行对代码的attention block进行了修改，使得它保持跟[STSA-Net论文](https://www.sciencedirect.com/science/article/pii/S0925231222013716)描述的保持一致。具体是：（1）根据4.2. Experimental Setting修改了超参；（2）根据Fig.2把原来sttformer每个[block](https://github.com/heleiqiu/STTFormer/blob/main/model/sta_block.py)的最后一层卷积换成了图里的ISAA（即multi-scale temporal conv）。因为改的不多，如果要复现应该也很简单。

不知能否解答您的问题？

**Comment by zangtuo** [comment]
感谢您的回复，对我帮助很大，很少有人认真回复，祝学习工作顺利。
