### ISSUE TITLE
请问可以提供h2o数据集上的权重吗

### ISSUE THREAD

**Issue by renyuanzhe** [Necolizer/ISTA-Net#7]
尊敬的作者您好，我按照仓库中的设置复现了实验，但提交给h2o网站时发现没法达到论文中的百分之90左右的准确率。请问您在训练时有什么技巧，或能否提供相关的权重文件呢，谢谢！

**Comment by Necolizer** [comment]
- 我当年训的其中一个权重文件及其推理得到的json：https://huggingface.co/Necolizer/ISTA-Net/tree/main/h2o
- 上述权重文件在验证集的准确率约为95.08%，在测试集的准确率约为91.73%
- 我印象中曾在两个不同服务器（3070/3080Ti）都训练及测试过，均能得到90%左右的准确率
- 我没有使用别的更多技巧，全部代码已经上传

**Comment by renyuanzhe** [comment]
感谢回复，在改了随机种子后模型表现正常了
